name: Tests

on:
  push:
    branches: [ main, develop, test ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true  # 改回嚴格模式
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .  # This will install from pyproject.toml
        pip install pytest pytest-cov pytest-mock  # Test dependencies
    
    - name: Run tests
      run: |
        python -c "import sys; print('Python version:', sys.version)"
        python -c "import pandas as pd; print('Pandas version:', pd.__version__)"
        python -c "import networkx as nx; print('NetworkX version:', nx.__version__)"
        ls -la tests/ || echo "Tests directory not found"
        python -m pytest tests/ -v --tb=short